from evoltier.optimizers import gaussian_natural_gradient
from evoltier.optimizers import cma_es
from evoltier.optimizers import bernoulli_natural_gradient
GaussianNaturalGradientOptimizer = gaussian_natural_gradient.GaussianNaturalGradientOptimizer
CMAES = cma_es.CMAES
BernoulliNaturalGradientOptimizer = bernoulli_natural_gradient.BernoulliNaturalGradientOptimizer